set(PROJECT_DISPLAY_NAME "QWCX")
set(PROJECT_NAME "QWCX")
set(PROJECT_NAME_CAMELCASE "QWCX")
set(PROJECT_NAME_LOWERCASE "qwcx")

set(PROJECT_VERSION_MAJOR "1")
set(PROJECT_VERSION_MINOR "0")
set(PROJECT_VERSION_PATCH "0")
set(PROJECT_VERSION_TWEAK "") # MUST be empty!
set(PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")
